/* eslint-disable */
// This file was generated by remotion.generate-asset-map.js

export const assetMap = {
  "static/audio/sound/boom.mp3": {
    "type": "MP3",
    "durationMs": 1306
  },
  "static/audio/sound/discord.mp3": {
    "type": "MP3",
    "durationMs": 504
  },
  "static/audio/sound/error.mp3": {
    "type": "MP3",
    "durationMs": 1018
  },
  "static/audio/sound/follow_1.mp3": {
    "type": "MP3",
    "durationMs": 2089
  },
  "static/audio/sound/get-out.mp3": {
    "type": "MP3",
    "durationMs": 863
  },
  "static/audio/sound/huh.mp3": {
    "type": "MP3",
    "durationMs": 624
  },
  "static/audio/sound/ios_received.mp3": {
    "type": "MP3",
    "durationMs": 2040
  },
  "static/audio/sound/ios_received_original.mp3": {
    "type": "MP3",
    "durationMs": 6384
  },
  "static/audio/sound/ios_sent.mp3": {
    "type": "MP3",
    "durationMs": 504
  },
  "static/audio/sound/knock.mp3": {
    "type": "MP3",
    "durationMs": 9168
  },
  "static/audio/sound/like_1.mp3": {
    "type": "MP3",
    "durationMs": 2089
  },
  "static/audio/sound/punch.mp3": {
    "type": "MP3",
    "durationMs": 1567
  },
  "static/audio/sound/wow.mp3": {
    "type": "MP3",
    "durationMs": 4205
  },
  "static/image/.local/under-water.png": {
    "type": "PNG"
  },
  "static/image/chatsnap.png": {
    "type": "PNG"
  },
  "static/image/imessage.png": {
    "type": "PNG"
  },
  "static/image/ios_contact-image.webp": {
    "type": "WEBP"
  },
  "static/image/memoji/1.png": {
    "type": "PNG"
  },
  "static/image/overlay/tiktok.png": {
    "type": "PNG"
  },
  "static/video/.local/baking_MrCakesOfficial_1.mp4": {
    "type": "MP4",
    "durationMs": 12100
  },
  "static/video/.local/baking_MrCakesOfficial_2.mp4": {
    "type": "MP4",
    "durationMs": 8400
  },
  "static/video/.local/baking_MrCakesOfficial_3.mp4": {
    "type": "MP4",
    "durationMs": 10566
  },
  "static/video/.local/baking_SatisfyingCakes_1.mp4": {
    "type": "MP4",
    "durationMs": 6033
  },
  "static/video/.local/baking_SoTastyOfficial_1.mp4": {
    "type": "MP4",
    "durationMs": 6000
  },
  "static/video/.local/cake-cutting_MrCakesOfficial_1.mp4": {
    "type": "MP4",
    "durationMs": 1233
  },
  "static/video/.local/cake-cutting_MrCakesOfficial_10.mp4": {
    "type": "MP4",
    "durationMs": 10766
  },
  "static/video/.local/cake-cutting_MrCakesOfficial_11.mp4": {
    "type": "MP4",
    "durationMs": 9900
  },
  "static/video/.local/cake-cutting_MrCakesOfficial_2.mp4": {
    "type": "MP4",
    "durationMs": 1700
  },
  "static/video/.local/cake-cutting_MrCakesOfficial_3.mp4": {
    "type": "MP4",
    "durationMs": 1900
  },
  "static/video/.local/cake-cutting_MrCakesOfficial_4.mp4": {
    "type": "MP4",
    "durationMs": 11533
  },
  "static/video/.local/cake-cutting_MrCakesOfficial_5.mp4": {
    "type": "MP4",
    "durationMs": 9200
  },
  "static/video/.local/cake-cutting_MrCakesOfficial_6.mp4": {
    "type": "MP4",
    "durationMs": 11933
  },
  "static/video/.local/cake-cutting_MrCakesOfficial_7.mp4": {
    "type": "MP4",
    "durationMs": 10633
  },
  "static/video/.local/cake-cutting_MrCakesOfficial_8.mp4": {
    "type": "MP4",
    "durationMs": 11600
  },
  "static/video/.local/cake-cutting_MrCakesOfficial_9.mp4": {
    "type": "MP4",
    "durationMs": 11933
  },
  "static/video/.local/cake-cutting_SatisfyingCakes_1.mp4": {
    "type": "MP4",
    "durationMs": 9900
  },
  "static/video/.local/cake-cutting_SoTastyOfficial_1.mp4": {
    "type": "MP4",
    "durationMs": 8200
  },
  "static/video/.local/hydraulic-press_hpc--official-26.mp4": {
    "type": "MP4",
    "durationMs": 5300
  },
  "static/video/.local/hydraulic-press_hpc--official-27.mp4": {
    "type": "MP4",
    "durationMs": 8800
  },
  "static/video/.local/hydraulic-press_hpc--official-28.mp4": {
    "type": "MP4",
    "durationMs": 7233
  },
  "static/video/.local/hydraulic-press_hpc--official-29.mp4": {
    "type": "MP4",
    "durationMs": 3466
  },
  "static/video/.local/hydraulic-press_hpc--official_1.mp4": {
    "type": "MP4",
    "durationMs": 2900
  },
  "static/video/.local/hydraulic-press_hpc--official_10.mp4": {
    "type": "MP4",
    "durationMs": 5733
  },
  "static/video/.local/hydraulic-press_hpc--official_11.mp4": {
    "type": "MP4",
    "durationMs": 3566
  },
  "static/video/.local/hydraulic-press_hpc--official_12.mp4": {
    "type": "MP4",
    "durationMs": 2333
  },
  "static/video/.local/hydraulic-press_hpc--official_13.mp4": {
    "type": "MP4",
    "durationMs": 2733
  },
  "static/video/.local/hydraulic-press_hpc--official_14.mp4": {
    "type": "MP4",
    "durationMs": 3600
  },
  "static/video/.local/hydraulic-press_hpc--official_15.mp4": {
    "type": "MP4",
    "durationMs": 2600
  },
  "static/video/.local/hydraulic-press_hpc--official_16.mp4": {
    "type": "MP4",
    "durationMs": 4400
  },
  "static/video/.local/hydraulic-press_hpc--official_17.mp4": {
    "type": "MP4",
    "durationMs": 1900
  },
  "static/video/.local/hydraulic-press_hpc--official_18.mp4": {
    "type": "MP4",
    "durationMs": 2600
  },
  "static/video/.local/hydraulic-press_hpc--official_19.mp4": {
    "type": "MP4",
    "durationMs": 3766
  },
  "static/video/.local/hydraulic-press_hpc--official_2.mp4": {
    "type": "MP4",
    "durationMs": 3400
  },
  "static/video/.local/hydraulic-press_hpc--official_20.mp4": {
    "type": "MP4",
    "durationMs": 5100
  },
  "static/video/.local/hydraulic-press_hpc--official_21.mp4": {
    "type": "MP4",
    "durationMs": 5566
  },
  "static/video/.local/hydraulic-press_hpc--official_22.mp4": {
    "type": "MP4",
    "durationMs": 2166
  },
  "static/video/.local/hydraulic-press_hpc--official_23.mp4": {
    "type": "MP4",
    "durationMs": 3000
  },
  "static/video/.local/hydraulic-press_hpc--official_24.mp4": {
    "type": "MP4",
    "durationMs": 3800
  },
  "static/video/.local/hydraulic-press_hpc--official_25.mp4": {
    "type": "MP4",
    "durationMs": 1933
  },
  "static/video/.local/hydraulic-press_hpc--official_3.mp4": {
    "type": "MP4",
    "durationMs": 13833
  },
  "static/video/.local/hydraulic-press_hpc--official_4.mp4": {
    "type": "MP4",
    "durationMs": 14000
  },
  "static/video/.local/hydraulic-press_hpc--official_5.mp4": {
    "type": "MP4",
    "durationMs": 8200
  },
  "static/video/.local/hydraulic-press_hpc--official_6.mp4": {
    "type": "MP4",
    "durationMs": 2733
  },
  "static/video/.local/hydraulic-press_hpc--official_7.mp4": {
    "type": "MP4",
    "durationMs": 1700
  },
  "static/video/.local/hydraulic-press_hpc--official_8.mp4": {
    "type": "MP4",
    "durationMs": 3033
  },
  "static/video/.local/hydraulic-press_hpc--official_9.mp4": {
    "type": "MP4",
    "durationMs": 2800
  },
  "static/video/.local/minecraft_BennoBuilder_1.mp4": {
    "type": "MP4",
    "durationMs": 67666
  },
  "static/video/.local/steep_BennoBuilder_1.mp4": {
    "type": "MP4",
    "durationMs": 165466
  },
  "static/video/.local/steep_BennoBuilder_2.mp4": {
    "type": "MP4",
    "durationMs": 85033
  },
  "static/video/.local/steep_BennoBuilder_3.mp4": {
    "type": "MP4",
    "durationMs": 67566
  },
  "static/video/.local/steep_BennoBuilder_4.mp4": {
    "type": "MP4",
    "durationMs": 59800
  },
  "static/video/.local/steep_BennoBuilder_5.mp4": {
    "type": "MP4",
    "durationMs": 205166
  },
  "static/video/.local/steep_BennoBuilder_6.mp4": {
    "type": "MP4",
    "durationMs": 69033
  },
  "static/video/.local/steep_BennoBuilder_7.mp4": {
    "type": "MP4",
    "durationMs": 232966
  },
  "static/video/.local/steep_BennoBuilder_8.mp4": {
    "type": "MP4",
    "durationMs": 100633
  },
  "static/video/.local/steep_BennoBuilder_9.mp4": {
    "type": "MP4",
    "durationMs": 104933
  }
};