/* eslint-disable */
// This file was generated by remotion.generate-asset-map.js

export const assetMap = {
  "static/audio/sound/boom.mp3": {
    "type": "MP3",
    "durationMs": 1306
  },
  "static/audio/sound/discord.mp3": {
    "type": "MP3",
    "durationMs": 504
  },
  "static/audio/sound/error.mp3": {
    "type": "MP3",
    "durationMs": 1018
  },
  "static/audio/sound/follow_1.mp3": {
    "type": "MP3",
    "durationMs": 2089
  },
  "static/audio/sound/get-out.mp3": {
    "type": "MP3",
    "durationMs": 863
  },
  "static/audio/sound/huh.mp3": {
    "type": "MP3",
    "durationMs": 624
  },
  "static/audio/sound/ios_received.mp3": {
    "type": "MP3",
    "durationMs": 2040
  },
  "static/audio/sound/ios_received_original.mp3": {
    "type": "MP3",
    "durationMs": 6384
  },
  "static/audio/sound/ios_sent.mp3": {
    "type": "MP3",
    "durationMs": 504
  },
  "static/audio/sound/knock.mp3": {
    "type": "MP3",
    "durationMs": 9168
  },
  "static/audio/sound/like_1.mp3": {
    "type": "MP3",
    "durationMs": 2089
  },
  "static/audio/sound/punch.mp3": {
    "type": "MP3",
    "durationMs": 1567
  },
  "static/audio/sound/wow.mp3": {
    "type": "MP3",
    "durationMs": 4205
  },
  "static/image/.local/under-water.png": {
    "type": "PNG"
  },
  "static/image/chatsnap.png": {
    "type": "PNG"
  },
  "static/image/imessage.png": {
    "type": "PNG"
  },
  "static/image/memoji/1.png": {
    "type": "PNG"
  },
  "static/image/overlay/tiktok.png": {
    "type": "PNG"
  },
  "static/midi/mission-impossible.mid": {
    "type": "MID"
  },
  "static/midi/mission-impossible_split.mid": {
    "type": "MID"
  },
  "static/midi/simple.mid": {
    "type": "MID"
  },
  "static/video/.local/minecraft_1.mp4": {
    "type": "MP4",
    "durationMs": 67666
  },
  "static/video/.local/steep_1.mp4": {
    "type": "MP4",
    "durationMs": 165466
  },
  "static/video/.local/steep_10.mp4": {
    "type": "MP4",
    "durationMs": 122700
  },
  "static/video/.local/steep_11.mp4": {
    "type": "MP4",
    "durationMs": 106866
  },
  "static/video/.local/steep_12.mp4": {
    "type": "MP4",
    "durationMs": 162900
  },
  "static/video/.local/steep_13.mp4": {
    "type": "MP4",
    "durationMs": 136733
  },
  "static/video/.local/steep_14.mp4": {
    "type": "MP4",
    "durationMs": 119000
  },
  "static/video/.local/steep_15.mp4": {
    "type": "MP4",
    "durationMs": 141933
  },
  "static/video/.local/steep_16.mp4": {
    "type": "MP4",
    "durationMs": 209133
  },
  "static/video/.local/steep_2.mp4": {
    "type": "MP4",
    "durationMs": 85033
  },
  "static/video/.local/steep_3.mp4": {
    "type": "MP4",
    "durationMs": 67566
  },
  "static/video/.local/steep_4.mp4": {
    "type": "MP4",
    "durationMs": 59800
  },
  "static/video/.local/steep_5.mp4": {
    "type": "MP4",
    "durationMs": 205166
  },
  "static/video/.local/steep_6.mp4": {
    "type": "MP4",
    "durationMs": 69033
  },
  "static/video/.local/steep_7.mp4": {
    "type": "MP4",
    "durationMs": 232966
  },
  "static/video/.local/steep_8.mp4": {
    "type": "MP4",
    "durationMs": 100633
  },
  "static/video/.local/steep_9.mp4": {
    "type": "MP4",
    "durationMs": 104933
  }
};